### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mymphe** [lidofinance/lido-ethereum-sdk#37]
- missing the "Prerequisites" section
- missing the "Contributing" section explaining how to set up the project locally, submit PRs, etc.;
- missing badges;
- considering adding a Features section;
- consider adding a roadmap section with some of the upcoming features.

**Comment by Jeday** [comment]
I think this will be done after me move docs to `docusaurus` freeing up readme.

**Comment by Yhamskie30** [comment]
#95

**Comment by dinhtuananhne** [comment]
#

**Comment by Jaycat66** [comment]
[Uploading token-econ (2).pdf…]()
[Uploading Crypto  TRADEABLE ASSETS.xlsx…]()

**Comment by Jeday** [comment]
Checkout https://lidofinance.github.io/lido-ethereum-sdk/
